version: "3.7"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: coins
      POSTGRES_DB: coins
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - '5432:5432'